((nil .  ((indent-tabs-mode . nil)))
 (c++-mode . ((indent-tabs-mode . nil)
              (c-indentation-style . "gnu")
              (c-file-offsets . ((inextern-lang . 0)
                                 (innamespace . 0))))))
